zuul:
  routes:
    users:
      path: /users/**
      service-id: users
#      strip-prefix: false    // this removes "/users" prefix
#      url: http://localhost:8081
    products:
      path: /products/** 
      service-id: products
#      url: http://localhost:8082  // dont use hard code ips instead use service ids. this makes service to run on different machine possible
#                                  // without any code change
    orders: 
      path: /orders/**
      service-id: orders
#      strip-prefix: false
#      url: http://localhost:8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root

  application:
    name: api-gateway

oauth:
  accesstoken:
    validity-seconds: 600

#security:
#  oauth2:
#    resource:
#      filter-order: 3
# added this order at WebSecurityConfig in java config @Order annotation
# https://stackoverflow.com/questions/44171633/spring-boot-oauth2-access-is-denied-user-is-anonymous-redirecting-to-authen?rq=1
# https://stackoverflow.com/questions/42822875/springboot-1-5-x-security-oauth2
# check more on filter orders

#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.cloud: DEBUG
#    org.springframework.web: DEBUG
