zuul:
  routes:
    users:
      service-id: users
#      url: http://localhost:8081
    products: 
      service-id: products
#      url: http://localhost:8082  // dont use hard code ips instead use service ids. this makes service to run on different machine possible
#                                  // without any code change
    orders: 
#      url: http://localhost:8083
      service-id: orders

eureka:
  client:
    service-url:
      defaultZone: http://192.168.9.10:8761/eureka/
      
server:
  port: 8080
