spring:

  application:
    name: users

  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
