spring:

  application:
    name: orders

  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: appuser
    password: appuser
    
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

service:
  product:
    serviceId: products

logging:
  file: C:\Umang\sws\microservices\logs\order-service.log
