spring:

  application:
    name: orders

  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: root
    
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
