spring:

  application:
    name: products

  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: root
    
server:
  port: 8082
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


# use below for setting different profile in single application.yml file 
#---
#spring: 
#  profiles: product-test
  